version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    depends_on:
      - php
      - mariadb
    volumes:
      - ./www:/usr/share/nginx/html
    ports:
      - "8080:80"
      - "443:443"
  
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./www:/usr/share/nginx/html
